services:
  bitwarden-sync:
    image: gabrielecabrini/bitwarden-sync:latest
    build:
      dockerfile: .
    container_name: bitwarden-sync
    restart: always
    environment:
      - CRON_SCHEDULE=0 0 * * *
      - BW_TAR_PASS=your_backup_password
      - BW_ACCOUNT_SOURCE=mybitwardensource@email.com
      - BW_PASS_SOURCE=mybitwardensourcepassword
      - BW_CLIENTID_SOURCE=user.32323232-3232323-232323-3232323-32323232
      - BW_CLIENTSECRET_SOURCE=FdfdfdfdfdfdfFfdfdffdfdfd
      - BW_SERVER_SOURCE=https://vault.mydomain.com
      - BW_ACCOUNT_DEST=mybitwardendest@email.com
      - BW_PASS_DEST=mybitwardendestpassword
      - BW_CLIENTID_DEST=user.1221212-121212-12121-12121
      - BW_CLIENTSECRET_DEST=Dsfdfdfdfdfdfdfdfdfgfdfdfds
      - BW_SERVER_DEST=https://vault.bitwarden.com
    # Optional bind mount encrypted backups
    volumes:
      - ./config/backups:/app/backups